### ISSUE TITLE
Remove the parentheses around the "view" parameter

### ISSUE THREAD

**Issue by shahheet31** [rilling/OpenTracksConcordia#112]
**Describe the Technical Debt**
Removed the parentheses around the view parameter.
Location - src/main/java/de/dennisguse/opentracks/TrackListActivity.java

![Issue Screenshot](https://github.com/rilling/OpenTracksConcordia/assets/45451213/97717571-550b-444d-913b-787f370ccbca)
The parentheses around the view parameter have been removed.

The potential consequences of this issue:
(1) Readability.
(2) Style Consistency.
(3) Misleading Other Developers.
(4) Potential Code Review Comments.
(5) Increased Code Length.

This needs to be fixed because:
(1) Maintainability in the Long Run.
(2) Improved Code Reviews.

**Proposed solution**

![Difference in the code](https://github.com/rilling/OpenTracksConcordia/assets/45451213/d9f51b4e-bdb4-4b68-965f-6898958429d6)

**Technical information**
 - Device: Dell G3 3579
 - OS: Windows 11
 - OpenTracks version: [e.g. v3.2.4]
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

**Comment by MalaySheth** [comment]
Solved
