### ISSUE TITLE
Rename this local variable to match the regular expression '^[a-z][a-zA-Z0-9]*S'

### ISSUE THREAD

**Issue by VarunAggarwal1998** [rilling/OpenTracksConcordia#147]
Location: src/main/java/de/dennisguse/opentracks/share/DescriptionGenerator.java

Rename the local variable "altitude_m" to match the regular expression '^[a-z][a-zA-Z0-9]*S'
<img width="1043" alt="Screenshot 2023-10-14 at 12 51 10 AM" src="https://github.com/rilling/OpenTracksConcordia/assets/117046986/2aede874-a48f-474b-a033-1b79ec308260">

**Technical information**
 - Device: [e.g. Nexus 7 (2013)]
 - OS: [e.g. LineageOS 15.1]
 - OpenTracks version: [e.g. v3.2.4]
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

**Comment by sehgaldeepanshu985** [comment]
Issue fixed and pushed in "Group_8" branch .

Proposed  Solution :
<img width="1043" alt="Screenshot 2023-10-14 at 12 58 24 AM" src="https://github.com/rilling/OpenTracksConcordia/assets/41449411/8b59f09a-5e86-46a7-a990-df1412af9d7e">
