### ISSUE TITLE
Part 2: Define the options and values for the new settings; #187 - subtask.

### ISSUE THREAD

**Issue by VarunAggarwal1998** [rilling/OpenTracksConcordia#200]
This subtask is for the enhancement #187 .
Define the options and values for the new settings
Make the necessary changes in src/main/res/values/settings.xml
After making the necessary changes ,merge it with the branch [187-update-default-units-in-settings_Group_8_C2]

**Comment by sehgaldeepanshu985** [comment]
The above changes are committed and pushed toe the mentioned branch.
Commit Link: https://github.com/rilling/OpenTracksConcordia/commit/9773c06bab404b293d48ca6e0f20e22355e6335d
