### ISSUE TITLE
Part 3: Add the corresponding ListPreference items for the updated settings; #187 - subtask.

### ISSUE THREAD

**Issue by VarunAggarwal1998** [rilling/OpenTracksConcordia#201]
This subtask is for the enhancement #187 .
Add the corresponding ListPreference items for the updated settings
Make the necessary changes in src/main/res/xml/settings_defaults.xml
After making the necessary changes ,merge it with the branch [187-update-default-units-in-settings_Group_8_C2]

**Comment by jasmanpreet0209** [comment]
The above changes are committed and pushed to the mentioned branch.
Commit Link: https://github.com/rilling/OpenTracksConcordia/commit/ec631f6a95f4ab67ff02e492de1ee53ded54a82f
