### ISSUE TITLE
Part 4: Create a new enum WeightUnit ; #187 - subtask.

### ISSUE THREAD

**Issue by VarunAggarwal1998** [rilling/OpenTracksConcordia#202]
This subtask is for the enhancement #187 .
create a new enum WeightUnit which can be used throughout your app to manage weight unit preferences, ensuring consistency and type safety. For instance, when you load the preference from the settings, you can convert the stored string value to a WeightUnit enum value, and vice versa.
Location: src/main/java/de/dennisguse/opentracks/settings
After making the necessary changes ,merge it with the branch [187-update-default-units-in-settings_Group_8_C2]

**Comment by nishabhatia98** [comment]
The above changes are committed and pushed to the mentioned branch.
[Commit Link](https://github.com/rilling/OpenTracksConcordia/commit/5655e0824063b7a735ee7d063ef81ee7463448db)
