### ISSUE TITLE
Part 5: Create a new enum TemperatureUnit ; #187 - subtask.

### ISSUE THREAD

**Issue by VarunAggarwal1998** [rilling/OpenTracksConcordia#203]
This subtask is for the enhancement https://github.com/rilling/OpenTracksConcordia/issues/187 .
create a new enum TemperatureUnit which can be used throughout your app to manage Temperature unit preferences, ensuring consistency and type safety. For instance, when you load the preference from the settings, you can convert the stored string value to a TemperatureUnit enum value, and vice versa.
Location: src/main/java/de/dennisguse/opentracks/settings
After making the necessary changes ,merge it with the branch [187-update-default-units-in-settings_Group_8_C2]

**Comment by knvramana** [comment]
The above changes are committed and pushed to the mentioned branch.
Commit Link: https://github.com/rilling/OpenTracksConcordia/commit/3e80dc03fbc7f8045a5f88caa757c1555af7696b
