### ISSUE TITLE
Part 7: Managing and retrieving the unit system preferences for Temperature unit; #187 - subtask.

### ISSUE THREAD

**Issue by VarunAggarwal1998** [rilling/OpenTracksConcordia#205]
This subtask is for the enhancement https://github.com/rilling/OpenTracksConcordia/issues/187 .
Add new methods used for managing and retrieving the unit system preferences within the app, allowing for dynamic changes in the unit display based on user preference or locale.
Location: src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
After making the necessary changes ,merge it with the branch [187-update-default-units-in-settings_Group_8_C2]

**Comment by habeebdashti** [comment]
The above changes are committed and pushed to the mentioned branch.
Commit Link: https://github.com/rilling/OpenTracksConcordia/commit/55fa4d31b89da271ff1f62bc807900d834ec5151
