### ISSUE TITLE
Part 1: Add User Profile Option in settings and icons

### ISSUE THREAD

**Issue by madhavtripathi05** [rilling/OpenTracksConcordia#211]
This sub-task is for the enhancement - Issue https://github.com/rilling/OpenTracksConcordia/issues/186
Added components for navigating to the new user profile screen in the main settings page.
Location : src/main/res/xml/settings.xml,  src/main/res/values/strings.xml and src/main/res/drawable/user_profile.xml
After making the necessary changes, merged it with the branch [group_9_case_2]

**Comment by navjyot11singh** [comment]
![Uploading image.png…]()

**Comment by navjyot11singh** [comment]
![Screenshot_20231125_202030](https://github.com/rilling/OpenTracksConcordia/assets/32342012/0cdca401-4b45-496a-a423-92c820f62f76)
