### ISSUE TITLE
Part 2: Add blank fragment and add initial title

### ISSUE THREAD

**Issue by madhavtripathi05** [rilling/OpenTracksConcordia#212]
This subtask is related to the enhancement of the original issue https://github.com/rilling/OpenTracksConcordia/issues/186.

Add blank fragment and add initial title

File Locations:

src/main/java/de/dennisguse/opentracks/settings/MainSettingsFragment.java
src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
 

Make necessary changes and commit the updated code in the branch [group_9_case_2]

**Comment by yashc1** [comment]
Added 2 new files and an empty component for the User profile:

src/main/java/de/dennisguse/opentracks/settings/UserProfileSettingsFragment.java
src/main/res/xml/settings_user_profile.xml

Commit: 72a6412a18454fef0ac9ed3c3771570e48de106b

Here are the screenshots after the code change:

![image](https://github.com/rilling/OpenTracksConcordia/assets/25180484/3c9996d3-991a-4047-b34c-2a4bff5fee6e)

![image](https://github.com/rilling/OpenTracksConcordia/assets/25180484/81b7a08a-ef2e-4128-845e-c80a7e8b028e)
