### ISSUE TITLE
Part 3: Add gender field in User Profile #186 - subtask

### ISSUE THREAD

**Issue by madhavtripathi05** [rilling/OpenTracksConcordia#213]
This subtask is related to the enhancement of the original issue https://github.com/rilling/OpenTracksConcordia/issues/186.

Add a component to select Gender for the User and store it locally which can then be used by other components of the app.

File Location: src/main/res/xml/settings_user_profile.xml

Make necessary changes and commit the updated code in the branch [group_9_case_2]

**Comment by kevinpandya** [comment]
Added dropdown menu to select Gender in the User Profile

![Screenshot 2023-11-19 150418](https://github.com/rilling/OpenTracksConcordia/assets/47737130/aac079b6-75f4-4753-9ac3-a3d633ba910a)

**Comment by kevinpandya** [comment]
The changes have been committed and pushed to the branch [group_9_case_2]

Commit Link: d42b9ff6e496bda6858347844d2b27b440b51d64
