### ISSUE TITLE
Part 4: Add Date of birth option in User profile; #186 - subtask.

### ISSUE THREAD

**Issue by madhavtripathi05** [rilling/OpenTracksConcordia#214]
This subtask is for the enhancement https://github.com/rilling/OpenTracksConcordia/issues/186 .
Add components for choosing the Date of birth and storing it in local storage to be used by other parts of the app.
Location: src/main/res/xml/settings_user_profile.xml
After making the necessary changes, merge it with the branch [group_9_case_2]

**Comment by madhavtripathi05** [comment]
Added DOB input field
![image](https://github.com/rilling/OpenTracksConcordia/assets/22491498/c3189530-f089-4afc-b9f7-692579a5bbf4)

**Comment by madhavtripathi05** [comment]
The above changes are committed and pushed to the mentioned branch.
Commit Link: https://github.com/rilling/OpenTracksConcordia/commit/32c4955538772ce0d82e7e55fd091c73a851e1d9

**Comment by kevin3010** [comment]
Commit : https://github.com/rilling/OpenTracksConcordia/commit/695c4477d40caadf7d62d8cec76d9f8d6cda5e11
