### ISSUE TITLE
Part 5: Add Age input in the user profile section

### ISSUE THREAD

**Issue by madhavtripathi05** [rilling/OpenTracksConcordia#215]
This subtask is for the enhancement https://github.com/rilling/OpenTracksConcordia/issues/186 .

Add a component in User Profile tab to store the Age of the user.

Location: src/main/res/xml/settings_user_profile.xml

Feature Branch : group_9_case_2

**Comment by kevin3010** [comment]
Added the Age Component

<img width="334" alt="image" src="https://github.com/rilling/OpenTracksConcordia/assets/42439376/9cead285-871a-453c-a2aa-6ab078c41fc7">

**Comment by kevin3010** [comment]
Commit : https://github.com/rilling/OpenTracksConcordia/commit/695c4477d40caadf7d62d8cec76d9f8d6cda5e11
