### ISSUE TITLE
Part 6: Add Weight option in User profile; #186 - subtask. 

### ISSUE THREAD

**Issue by madhavtripathi05** [rilling/OpenTracksConcordia#216]
This sub task is for the enhancement -  Issue https://github.com/rilling/OpenTracksConcordia/issues/186
Added components for imputing the Height (In kg) and saving it in local storage so that it can be used by the other parts of the app.
Location : src/main/res/xml/settings_user_profile.xml and src/main/res/values/strings.xml
After making the necessary changes, merged it with the branch [group_9_case_2]

**Comment by SayeedSanjana** [comment]
Added Weight option in the user file and pushed the code in the branch case_9_case_2

![final2](https://github.com/rilling/OpenTracksConcordia/assets/65913030/1c728654-068b-42c6-832e-759012df20c2)

![final1](https://github.com/rilling/OpenTracksConcordia/assets/65913030/cc0c318e-6c44-4fa2-975e-5261c3240f2b)

Commit Link: [cda55b2](https://github.com/rilling/OpenTracksConcordia/commit/cda55b248c36fd311f1126d46174b9c09722e144)

**Comment by SayeedSanjana** [comment]
The changes are pushed in the branch [group_9_case_2]
Commit Link: [cda55b2](https://github.com/rilling/OpenTracksConcordia/commit/cda55b248c36fd311f1126d46174b9c09722e144)
