### ISSUE TITLE
Part 7: Add Height option in User profile; #186 - subtask.

### ISSUE THREAD

**Issue by madhavtripathi05** [rilling/OpenTracksConcordia#217]
This subtask is for the enhancement
[Issue 186](https://github.com/rilling/OpenTracksConcordia/issues/186) 
Add components for adding the Height (In Centimeters) and saving it in local storage so that it can be used by the other parts of the app.
Location: src/main/res/xml/settings_user_profile.xml and src/main/res/values/strings.xml
After making the necessary changes, merge it with the branch [group_9_case_2]

**Comment by purveshsakhiya9** [comment]
![Screenshot_20231119_155909](https://github.com/rilling/OpenTracksConcordia/assets/48780962/a32fc2b4-ba08-4473-aa1b-18293f968e87)

The above changes are committed and pushed to the mentioned branch.
Commit Link: https://github.com/rilling/OpenTracksConcordia/commit/9b9b7edef6f776ab3a6a52a1189971fb2bbb8b5d
