### ISSUE TITLE
Subtask 3: Implement a Method to Fetch Weather Data from Latitude and Longitude

### ISSUE THREAD

**Issue by hardik221** [rilling/OpenTracksConcordia#233]
### **Description**
This subtask is for the enhancement https://github.com/rilling/OpenTracksConcordia/issues/189 .

Implement a Method to Fetch Weather Data from Latitude and Longitude

**Location:** `src\main\java\de\dennisguse\opentracks\services\WeatherFetchService.java`

After making the necessary changes, merge it with the branch [group_1_case_2]

**Comment by PrashantBanavali** [comment]
Code changes to fetch weather data implemented as required
