### ISSUE TITLE
Subtask 2: Update Opentracks to the latest version (at least 4.9)

### ISSUE THREAD

**Issue by dinesh-07** [rilling/OpenTracksConcordia#240]
This is sub task of https://github.com/rilling/OpenTracksConcordia/issues/180
Update Opentracks to the latest version (at least 4.9) to benefit from bug fixes and improvements.

**Comment by HarinderSinghRana** [comment]
Commit - https://github.com/rilling/OpenTracksConcordia/pull/304/commits/0d38bd239f1360c1235da666ee755826cd4bd72a

Screenshot of commit - 
<img width="1491" alt="Screenshot 2023-11-27 at 17 14 24" src="https://github.com/rilling/OpenTracksConcordia/assets/113846907/512a603d-a029-4b27-ad0d-568de3998ed8">
