### ISSUE TITLE
Subtask 2 : Change Start button functionalities.

### ISSUE THREAD

**Issue by pranjalesh** [rilling/OpenTracksConcordia#249]

**Comment by raahuljohn** [comment]
This is a subtask of the issue : https://github.com/rilling/OpenTracksConcordia/issues/192

The pull request for this task is linked here : https://github.com/rilling/OpenTracksConcordia/pull/198

Commit : [Link](https://github.com/rilling/OpenTracksConcordia/pull/198/commits/6ee8101195d692fecf93873372a4658d008936d7)
