### ISSUE TITLE
Subtask 5 : Modify hold to pause button to be more descriptive.

### ISSUE THREAD

**Issue by pranjalesh** [rilling/OpenTracksConcordia#252]
The existing hold-to-pause button was modified to be more descriptive and display a better design with a dark background tint and utilizing a monospace font. Its linked functionality dictates its behavior. 

**The link to the pull request is:** #198
**The commit link:** [Link](https://github.com/rilling/OpenTracksConcordia/commit/2038d42828b65caf6add6f5fe606d9f832ab8aa2)

**Comment by marium19** [comment]
Added the above-mentioned Subtask Title, subtask description and Links to the pull request and the commit made
