### ISSUE TITLE
Subtask 6 : Add a updated Start Button to the layout and style it accordingly.

### ISSUE THREAD

**Issue by pranjalesh** [rilling/OpenTracksConcordia#253]
## Defined a styled button with the text "START WORKOUT"
The button is crafted to align visually with the app's overarching design, displaying a dark background tint and utilizing a monospace font. Its behavior, including the actions triggered upon clicking the button, is determined by its associated functionality.

**Comment by prafulnair** [comment]
Added the above-mentioned Subtask Title, subtask description and Links to the pull request and the commit made
