### ISSUE TITLE
Subtask 7 : Make changes in Start button to better suit the requirements.

### ISSUE THREAD

**Issue by pranjalesh** [rilling/OpenTracksConcordia#254]
Revised the operation of the 'Stop' button to now function as a 'Pause' button within the 'HoldToStopButton' feature.

**Comment by urvishkapadiya** [comment]
This is a subtask of the issue #192 

The pull request for this task is linked here #198 

Commit [Link](https://github.com/rilling/OpenTracksConcordia/pull/198/commits/0f50770b20a122d66c84c2904ab672dc5789e1b7)
