### ISSUE TITLE
Subtask 3 : Add toggle “Distance”in the aggregated stats option under settings. 

### ISSUE THREAD

**Issue by alekhya-2000** [rilling/OpenTracksConcordia#258]
This subtask is for the enhancement [#182 ](https://github.com/rilling/OpenTracksConcordia/issues/182)
1. Display the "Distance" under Aggregated stats in setting options in open tracks
2. Add the toggle functionality in the Distance

**Comment by raghavmanchanda2** [comment]
Closing the issue, As the functionality:- "Add toggle -Distance in the aggregated stats option under settings" have been added with the following commit:- https://github.com/rilling/OpenTracksConcordia/commit/042d75ce5f58a795a7b1d0cb2e7413aae467527f

Build is also successful after the commit:- 
![image](https://github.com/rilling/OpenTracksConcordia/assets/53889865/4c8e6975-8ecc-4382-bf71-a2af0779d06e)
