### ISSUE TITLE
Subtask 4: Add toggle “Max Speed” in the aggregated stats option under settings.

### ISSUE THREAD

**Issue by alekhya-2000** [rilling/OpenTracksConcordia#259]
This subtask is for the enhancement [#182 ](https://github.com/rilling/OpenTracksConcordia/issues/182)

1. Display the " Max Speed" under Aggregated stats in setting options in open tracks
2. Add the toggle functionality in the Max Speed

**Comment by bhavya-bugude** [comment]
Snapshots of the implementation

Application Behaviour when Max Speed toggle is off:

![MaxSpeedOff](https://github.com/rilling/OpenTracksConcordia/assets/77609708/715f6307-4cab-4484-924f-1c7203ac193e)
![MaxSpeedOff1](https://github.com/rilling/OpenTracksConcordia/assets/77609708/f663feb2-ad26-48d0-9a1e-e12377f637ee)


Application behaviour when Max Speed toggle is On:

![MaxSpeedOn](https://github.com/rilling/OpenTracksConcordia/assets/77609708/1a45d32e-a24b-4068-8632-f4bb0b8656b0)
![MaxSpeedOn1](https://github.com/rilling/OpenTracksConcordia/assets/77609708/6f93cd9f-16c0-4028-8c9a-5314f8c70869)
