### ISSUE TITLE
Subtask 5: Add toggle “Moving Speed”in the aggregated stats option under settings

### ISSUE THREAD

**Issue by alekhya-2000** [rilling/OpenTracksConcordia#260]
This subtask is for the enhancement [#182 ](https://github.com/rilling/OpenTracksConcordia/issues/182)

1. Display the "Moving Speed" under Aggregated stats in setting options in open tracks
2. Add the toggle functionality in the Moving Time

**Comment by udisha0606** [comment]
Toggle Functionality has been added to the program for moving time.

**Comment by udisha0606** [comment]
Added toggle for Moving Speed
