### ISSUE TITLE
Subtask 8 : Display elevation gain under aggregated stats 

### ISSUE THREAD

**Issue by alekhya-2000** [rilling/OpenTracksConcordia#263]
This subtask is for the enhancement [#182 ](https://github.com/rilling/OpenTracksConcordia/issues/182)

1. Display the UI of Elevation gain under aggregated stats
2. Show the cumulative elevation increase in the aggregated statistics

**Comment by yashvadaria** [comment]
The commit id for this task is [64cff1f5770f752a48e170a9cf879fb09a0c1990](https://github.com/rilling/OpenTracksConcordia/commit/6cb2ea516bb45f85343fee407f9c78d8d1afd576)
