### ISSUE TITLE
SubTask 2: Make a function to return boolean based on user preference

### ISSUE THREAD

**Issue by anash3420** [rilling/OpenTracksConcordia#270]
SubTask linked to #181 
1. Take user preference from subtask #269 and make a function to return a boolean indicating whether to announce the current heart rate or not

**Comment by Rhmarwaha** [comment]
Made a function to return boolean based on user preference of voice and committed on group-7-181
[Commit Link](https://github.com/rilling/OpenTracksConcordia/commit/b754c8e3675ab9f8f76f131ba9eb3d786845fc43)
