### ISSUE TITLE
Subtask 5: Get user height from user preference

### ISSUE THREAD

**Issue by dinesh-07** [rilling/OpenTracksConcordia#286]
This is a sub-task of https://github.com/rilling/OpenTracksConcordia/issues/188

**Comment by sakethoppula** [comment]
The issue has been resolved by the following commit.
Pull request - https://github.com/rilling/OpenTracksConcordia/pull/294
![image](https://github.com/rilling/OpenTracksConcordia/assets/11327092/da2f4909-ce54-42e3-b2fc-8873216d29b6)

Commit - https://github.com/rilling/OpenTracksConcordia/pull/294/commits/9df88601057b15ca2859a27b251f014fd2eb4273
![image](https://github.com/rilling/OpenTracksConcordia/assets/11327092/ff525ac5-cc9d-46f8-83b8-3b8a8595aa61)
