### ISSUE TITLE
Issue 183 Subtask 1 - Top Navbar

### ISSUE THREAD

**Issue by denzz312** [rilling/OpenTracksConcordia#290]
This is a subtask for https://github.com/rilling/OpenTracksConcordia/issues/183

Is your feature request related to a problem? Please describe.
Current Start screen is not intuitive. Top Nav bar provides access to the various options including settings and help that could be really beneficial on the start screen.

Describe the solution you'd like
Making sure the top nav bar is  visible and working in the home screen.  The search button should not be present and markers shouldn't be there since it is not a task list anymore. Also it should have the settings and help in the submenu.

**Comment by amanpreetbatra** [comment]
Created a new top navbar for the new home screen:

![image](https://github.com/rilling/OpenTracksConcordia/assets/37112041/2d1492f5-3752-4621-9e44-5a1d2cdb254d)

Successfully routed the settings and help to settings activity and help activity:

![image](https://github.com/rilling/OpenTracksConcordia/assets/37112041/3df1795e-1491-4526-b3ee-6fc37c7af5b4)
