### ISSUE TITLE
Remove this use of "notifychange", it is deprecated

### ISSUE THREAD

**Issue by swetasarat2000** [rilling/OpenTracksConcordia#65]
**Describe the technical debt**

Addressed a sonar issue where notifyChange method should be updated to the newer method where it doesn't take false arguments.
Location : src/main/java/de/dennisguse/opentracks/data/CustomContentProvider.java

<img width="1465" alt="Screenshot 2023-10-07 at 8 37 09 PM" src="https://github.com/rilling/OpenTracksConcordia/assets/144390677/f8cdfe38-d412-471d-bdc5-8c35c3a362b4">

The third argument (the boolean flag) is removed, as it's no longer needed. The method notifyChange(url, null) is the modern and non-deprecated way to use this method.
The potential consequences of not addressing this issue :

1. Ignoring this issue could lead to data inconsistencies and loss of data integrity in the system.
2. Could result in reduced system efficiency
3. Vulnerable to security threats and unauthorised access

This needs to be fixed to:

1. Ensure data accuracy
2. Increase system performance

**Proposed solution**

Removed the third argument (false) from the 'notifychange' method.

<img width="1025" alt="Screenshot 2023-10-07 at 9 00 27 PM" src="https://github.com/rilling/OpenTracksConcordia/assets/144390677/5ba1c121-bd89-44fb-af89-2d4122cdab45">

**Technical information**
 - Device: [e.g. Nexus 7 (2013)]
 - OS: [e.g. LineageOS 15.1]
 - OpenTracks version: [e.g. v3.2.4]
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

**Comment by MalaySheth** [comment]
Solved
