### ISSUE TITLE
Replace this "switch" statement by "if" statements

### ISSUE THREAD

**Issue by denzz312** [rilling/OpenTracksConcordia#84]
**Describe the technical debt**
A clear and concise description of what the technical debt is.
Location: services/TrackDeleteService.java

**Proposed solution**

If applicable:
![Screenshot 2023-10-11 at 11 35 30 PM](https://github.com/rilling/OpenTracksConcordia/assets/49382147/d2409625-6df6-4334-b42b-79b58383e383)
* add logcat output

**Technical information**
 - Device: [e.g. Nexus 7 (2013)]
 - OS: [e.g. LineageOS 15.1]
 - OpenTracks version: [e.g. v3.2.4]
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

**Comment by abraredu11** [comment]
Replaced the SWITCH statement with corresponding IF ELSE.
Added a custom runtime exception class to prevent generic usage of it.
![Screenshot 2023-10-12 194149](https://github.com/rilling/OpenTracksConcordia/assets/119269038/6c9b71c7-7bb8-411a-906f-e41860572eb8)
![Screenshot 2023-10-12 194700](https://github.com/rilling/OpenTracksConcordia/assets/119269038/ae2fcaff-6b7d-4c5d-81c3-6e02804438ac)

**Comment by abraredu11** [comment]
#84 Replaced SWITCH with IF-ELSE statement and added a custom exception class to counter generic usage of exceptions
