### ISSUE TITLE
The type of the "toBeDeleted" object should be an interface such as "List"

### ISSUE THREAD

**Issue by denzz312** [rilling/OpenTracksConcordia#85]
**Describe the technical debt**
A clear and concise description of what the technical debt is.
Location: services/TrackDeleteService.java

**Proposed solution**

If applicable:
![Screenshot 2023-10-11 at 11 39 19 PM](https://github.com/rilling/OpenTracksConcordia/assets/49382147/9a9b3a3e-7476-4f9d-9689-f0af45a2cf7c)

* add logcat output

**Technical information**
 - Device: [e.g. Nexus 7 (2013)]
 - OS: [e.g. LineageOS 15.1]
 - OpenTracks version: [e.g. v3.2.4]
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

**Comment by amanpreetbatra** [comment]
Proposed Solution:
Changed the type of toBeDeleted from ArrayList to List so a wider range of objects can be passed and type-caste it to Arraylist to preserve the functionality of the code.
![Screenshot from 2023-10-13 17-09-28](https://github.com/rilling/OpenTracksConcordia/assets/37112041/e18e5efc-878b-44bc-bef6-bff287b5165f)
