### ISSUE TITLE
Remove this use of "getParcelableExtra"

### ISSUE THREAD

**Issue by denzz312** [rilling/OpenTracksConcordia#86]
**Describe the technical debt**
A clear and concise description of what the technical debt is.

**Proposed solution**

If applicable:
![Screenshot 2023-10-11 at 11 41 08 PM](https://github.com/rilling/OpenTracksConcordia/assets/49382147/f28d467d-5952-405a-996b-e225488e5ff6)

* add logcat output

**Technical information**
 - Device: [e.g. Nexus 7 (2013)]
 - OS: [e.g. LineageOS 15.1]
 - OpenTracks version: [e.g. v3.2.4]
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

**Comment by Mridul-11** [comment]
Issue resolved
Proposed solution:
Replaced 'getParcelableExtra' with 'getExtras().getParcelable()'
Replaced 'getParcelableArrayListExtra' with 'getExtras().getParcelableArrayList()'
![WhatsApp Image 2023-10-14 at 12 26 02 AM](https://github.com/rilling/OpenTracksConcordia/assets/110491087/11418fb7-23c1-4dd0-b487-85b06e17c65e)
